name: widgetbook_workspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: 3.7.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook: 3.12.0
  widgetbook_annotation: 3.3.1
  flutter_template_app:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  widgetbook_generator: 3.10.0
  build_runner: 2.4.15

dependency_overrides:
  analyzer: ^6.0.0
  freezed_annotation: 3.0.0

flutter:
  uses-material-design: true
